In [1]:
from __future__ import division, unicode_literals, print_function
import numpy as np
import pandas as pd

# 1. Pythonの基本
## 1.1. 組み込みのデータ型
* int ... 整数 (説明省略)
* float ... 小数 (説明省略)
* str ... 文字列
* list ... リスト
* tuple ... タプル (読み込み専用list．今回は省略)
* dict ... 辞書

### 1.1.1. str

In [2]:
text = "Hello World"
print(text)
print(text + '!!')  # 文字列を+すると文字が追加される

Hello World
Hello World!!


### 1.1.2. list

In [3]:
# listの参照
x = [2, 0, 1, 7]
print(x[0])  # 最初の要素
print(x[2])  # 3番目の要素
print(x[2:])  # 3番目以降の要素
print(x[:2])  # 3番目未満の要素
print(x[-1])  # 最後の要素

2
1
[1, 7]
[2, 0]
7


In [4]:
# listの操作
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
print(x + y)  # xとyが結合される
x.append(9999)
print(x)  # 9999が追加される
print(x.index(9999))  # 9999があるインデックスを教えてくれる

[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 9999]
4


### 1.1.3. dict

In [5]:
# dictの作成
d = {
    # key: value
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': 'こんにちは'
}
print(d['a'])  # 辞書の'a'には[1, 2, 3]が格納されている
print(d['c'])  # 辞書の'c'には'こんにちは'が格納されている
print(d['d'])  # 辞書には'd'が登録されていない

[1, 2, 3]
こんにちは


KeyError: 'd'

## 1.2. forとif
### 1.2.1. for

In [6]:
for i in [1, 2, 3]:
    print(i)

1
2
3


In [7]:
for i in range(3):  # range(3)は「0から始まる3要素のリスト (のようなもの)」を作成する
    print(i)

0
1
2


### 1.2.2. if

In [8]:
x = 3
if x == 3:
    print('x is 3')

x is 3


In [9]:
if x == 10:
    print('x is 10')
else:
    print('x is not 10')

x is not 10


In [10]:
if x == 10:
    print('x is 10')
elif x == 3:
    print('x is 3')
else:
    print('x is neither 3 and 10')

x is 3


In [11]:
if x in [1, 2, 3]:
    print('x is in the list')

x is in the list


## 1.3 NumPy
心理学実験・分析を行ううえで，組み込みデータ型を使うことは基本的にほとんど無い．

数値計算はほぼ全てNumPy，表の扱いはほぼ全てPandas (後述) で行う

### 1.3.1 四則演算

In [12]:
# numpy.arrayの四則演算
arr = np.array([1, 2, 3])
print(arr)  # ぱっと見listと変わらないが…
print(arr + 3)  # 足し算が可能
print(arr * 3)  # 掛け算もOK!

[1 2 3]
[4 5 6]
[3 6 9]


In [13]:
# numpy.arrayの多次元配列
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)  # listの入れ子で行列を表現できる

[[1 2 3]
 [4 5 6]]


### 1.3.2. 配列の作成

In [14]:
arr = np.zeros(2)
print(arr)  # 長さ2の，0のみの1次元配列

arr = np.ones([2, 4])
print(arr)  # 2行4列の，1のみの2次元配列

arr = np.random.random([2, 4])
print(arr)  # 2行4列の，乱数の3次元配列

[ 0.  0.]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 0.76700413  0.28117237  0.53067314  0.29738767]
 [ 0.64155516  0.86241723  0.14577944  0.02167225]]


### 1.3.3. 要素へのアクセス

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(arr[0, 0])  # 1行1列目．行→列の順にカンマ区切りで指定
print(arr[0, :])  # 1行目
print(arr[:, -1])  # 最後の列
print(arr[1:, :])  # 2行目以降

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[1 2 3]
[3 6 9]
[[4 5 6]
 [7 8 9]]


## 1.4. Pandas
Pandasはデータフレームの操作に特化している．Rのdata.frameとかなり類似した機能を持つ

In [16]:
df = pd.DataFrame(arr)  # データフレームの作成
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [17]:
df = pd.DataFrame(arr, index=['one', 'two', 'three'], columns=['eins', 'zwei', 'drei'])
print(df)  # 行名・列名を指定することができる

       eins  zwei  drei
one       1     2     3
two       4     5     6
three     7     8     9


In [18]:
print(df.loc['one', 'zwei'])  # 名前でアクセス (location)
print(df.iloc[0, 0])  # インデックスでアクセス (index location)

2
1
